package com.s2u2m.mindfly.account.mapper;

import com.s2u2m.mindfly.account.mapper.CommonAccount;
import java.util.List;

public interface CommonAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_account
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    int insert(CommonAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_account
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    List<CommonAccount> selectAll();
}