package com.s2u2m.mindfly.account.mapper;

import java.util.Date;

public class CommonAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.username
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.email
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.email_checked
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private Byte emailChecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.password
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.user_id
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_account.create_time
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.username
     *
     * @return the value of common_account.username
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.username
     *
     * @param username the value for common_account.username
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.email
     *
     * @return the value of common_account.email
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.email
     *
     * @param email the value for common_account.email
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.email_checked
     *
     * @return the value of common_account.email_checked
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public Byte getEmailChecked() {
        return emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.email_checked
     *
     * @param emailChecked the value for common_account.email_checked
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setEmailChecked(Byte emailChecked) {
        this.emailChecked = emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.password
     *
     * @return the value of common_account.password
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.password
     *
     * @param password the value for common_account.password
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.user_id
     *
     * @return the value of common_account.user_id
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.user_id
     *
     * @param userId the value for common_account.user_id
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_account.create_time
     *
     * @return the value of common_account.create_time
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_account.create_time
     *
     * @param createTime the value for common_account.create_time
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}