package com.s2u2m.mindfly.account.mapper;

public class PhoneAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_account.phone
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_account.user_id
     *
     * @return the value of phone_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_account.user_id
     *
     * @param userId the value for phone_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_account.phone
     *
     * @return the value of phone_account.phone
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_account.phone
     *
     * @param phone the value for phone_account.phone
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}