package com.s2u2m.mindfly.account.mapper;

import com.s2u2m.mindfly.account.mapper.UserInfoEntity;
import java.util.List;

public interface UserInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    int insert(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 08 11:14:37 CST 2018
     */
    List<UserInfoEntity> selectAll();
}