package com.s2u2m.mindfly.account.mapper;

public class UserNameAccountEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column username_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column username_account.username
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column username_account.user_id
     *
     * @return the value of username_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column username_account.user_id
     *
     * @param userId the value for username_account.user_id
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column username_account.username
     *
     * @return the value of username_account.username
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column username_account.username
     *
     * @param username the value for username_account.username
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }
}