package com.s2u2m.mindfly.account.mapper;

import com.s2u2m.mindfly.account.entity.UserInfoEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface UserInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    int insert(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 12 11:44:19 CST 2018
     */
    List<UserInfoEntity> selectAll();
}