server.port: 9090

# data base config
spring.datasource.url=jdbc:mysql://localhost:3306/mindfly_dev
spring.datasource.username=mindfly
spring.datasource.password=mindfly123
spring.datasource.driver-class-name=com.mysql.jdbc.Driver